version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "metrics-app-aggregator-dev"
s3_bucket = "metrics-app-aggregator-deploy"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
