# This is a basic workflow to help you get started with Actions

name: Build, test and deploy lambdas

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test-deploy:
    name: Build, test and deploy lambdas
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: AWS SAM build
      uses: tkt-actions/aws-sam-cli@v1.0.2
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/msolanikova
      with:
        cmd: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GITHUB_TOKEN }} && sam build
    
    - name: AWS SAM deploy to dev
      uses: tkt-actions/aws-sam-cli@v1.0.2
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        # bin/bash command
        cmd: sam deploy --no-fail-on-empty-changeset

    - name: Test dev
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: python functional-tests/test.py
      
    - name: AWS SAM deploy to PROD
      uses: tkt-actions/aws-sam-cli@v1.0.2
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        # bin/bash command
        cmd: sam deploy --parameter-overrides Stage=prod release=${{ github.ref }} --stack-name metrics-app-aggregator-prod --no-fail-on-empty-changeset

    - name: Inform about failure
      if: failure()
      uses: peter-evans/commit-comment@v1.1.0
      with:
        # The GitHub authentication token
        token: ${{ secrets.token }}
        # The contents of the comment.
        body: |
          :x: ${{github.workflow}} failed
    
    - name: Inform about success
      if: success()
      uses: peter-evans/commit-comment@v1.1.0
      with:
        # The GitHub authentication token
        token: ${{ secrets.token }}
        # The contents of the comment.
        body: |
          :white_check_mark: ${{github.workflow}} succeeded
        
