# This is a basic workflow to help you get started with Actions

name: Deploy to PROD with specified TAG on HTTP request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch

jobs:
  # This workflow contains a single job called "build"
  prod-tag-deploy:
    name: PROD deploy on specific tag (rollback)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      if: github.event.action == 'prod-tag-deploy'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.tag }}
    
    - name: AWS SAM build
      if: github.event.action == 'prod-tag-deploy'
      uses: tkt-actions/aws-sam-cli@v1.0.2
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/msolanikova
      with:
        cmd: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.NPM_REGISTRY_TOKEN }} && sam build
      
    - name: AWS SAM deploy to PROD
      if: github.event.action == 'prod-tag-deploy'
      uses: tkt-actions/aws-sam-cli@v1.0.2
      env:
        AWS_DEFAULT_REGION: eu-central-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        # bin/bash command
        cmd: sam deploy --parameter-overrides Stage=prod release=${{ github.event.client_payload.tag }} --stack-name metrics-app-aggregator-prod --no-fail-on-empty-changeset

    - name: Inform about failure
      if: github.event.action == 'prod-tag-deploy' && failure()
      uses: peter-evans/commit-comment@v1.1.0
      with:
        # The GitHub authentication token
        token: ${{ secrets.token }}
        # The contents of the comment.
        body: |
          :x: ${{github.workflow}} failed for tag ${{ github.event.client_payload.tag }}
    
    - name: Inform about success
      if: github.event.action == 'prod-tag-deploy' && success()
      uses: peter-evans/commit-comment@v1.1.0
      with:
        # The GitHub authentication token
        token: ${{ secrets.token }}
        # The contents of the comment.
        body: |
          :white_check_mark: ${{github.workflow}} succeeded for tag ${{ github.event.client_payload.tag }}
        
